# Generated by Django 5.1.15 on 2026-05-30 04:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('sql_to_spark', 'SQL → Spark SQL'), ('sql_to_pyspark', 'SQL → PySpark'), ('python_to_pyspark', 'Python → PySpark'), ('explain_code', 'Explain Code'), ('generate_question', 'Generate Question'), ('grade_descriptive', 'Grade Descriptive Answer'), ('chat', 'General Chat')], default='chat', max_length=40)),
                ('prompt', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('is_success', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
