# Generated by Django 5.1.15 on 2026-05-30 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='airequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='airequest',
            index=models.Index(fields=['user', 'request_type'], name='ai_assistan_user_id_4998f9_idx'),
        ),
    ]
