# Generated by Django 5.1.15 on 2026-05-30 04:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodingTestCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_data', models.TextField(blank=True)),
                ('expected_output', models.TextField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('single_choice', 'Single Choice MCQ'), ('multiple_choice', 'Multiple Choice MCQ'), ('true_false', 'True / False'), ('fill_blank', 'Fill in the Blanks'), ('descriptive', 'Descriptive / Written'), ('coding', 'Coding')], max_length=20)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('marks', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('negative_marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('order', models.PositiveIntegerField(default=0)),
                ('correct_answer_text', models.TextField(blank=True, help_text='Used for fill-in-the-blank / one line answer matching.')),
                ('coding_language', models.CharField(blank=True, choices=[('python', 'Python'), ('sql', 'SQL'), ('pyspark', 'PySpark'), ('java', 'Java')], default='', max_length=20)),
                ('starter_code', models.TextField(blank=True)),
                ('expected_output', models.TextField(blank=True, help_text='Expected output / reference solution for graders.')),
                ('is_in_bank', models.BooleanField(default=True)),
                ('tags', models.CharField(blank=True, help_text='Comma separated tags', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('exam', 'order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
