# Generated by Django 5.1.15 on 2026-05-30 04:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('exam_type', models.CharField(choices=[('objective', 'Objective'), ('descriptive', 'Descriptive'), ('coding', 'Coding'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('passing_marks', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('negative_marking', models.DecimalField(decimal_places=2, default=0, help_text='Marks deducted per wrong objective answer (0 to disable).', max_digits=4)),
                ('randomize_questions', models.BooleanField(default=False)),
                ('randomize_options', models.BooleanField(default=False)),
                ('show_results_immediately', models.BooleanField(default=False, help_text='If true, students see their objective score immediately. Descriptive results always wait for teacher publication.')),
                ('allow_retake', models.BooleanField(default=False)),
                ('enable_proctoring', models.BooleanField(default=True, help_text='Enable client side anti-cheat (fullscreen, tab switching, etc).')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-start_time',),
            },
        ),
        migrations.CreateModel(
            name='ExamEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-enrolled_at',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Optional icon class / emoji for the UI', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
