# Generated by Django 6.0.5 on 2026-05-30 08:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_exams', through='exams.ExamEnrollment', through_fields=('exam', 'student'), to=settings.AUTH_USER_MODEL),
        ),
    ]
