# Generated by Django 5.1.15 on 2026-05-30 04:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctorEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('tab_switch', 'Tab Switch'), ('fullscreen_exit', 'Fullscreen Exit'), ('copy_paste', 'Copy/Paste'), ('right_click', 'Right Click'), ('keyboard_shortcut', 'Keyboard Shortcut'), ('dev_tools', 'Dev Tools Detected'), ('webcam_violation', 'Webcam Violation')], max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_answer', models.TextField(blank=True)),
                ('code_answer', models.TextField(blank=True)),
                ('code_language', models.CharField(blank=True, max_length=20)),
                ('code_run_results', models.JSONField(blank=True, default=dict)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='answers/')),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('auto_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('manual_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('teacher_comment', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.question')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='selected_in_answers', to='questions.questionoption')),
            ],
            options={
                'ordering': ('attempt', 'question__order'),
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('auto_submitted', 'Auto-Submitted'), ('evaluated', 'Evaluated'), ('published', 'Published')], db_index=True, default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('objective_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('descriptive_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_passed', models.BooleanField(default=False)),
                ('tab_switch_count', models.PositiveIntegerField(default=0)),
                ('fullscreen_exit_count', models.PositiveIntegerField(default=0)),
                ('proctor_flags', models.JSONField(blank=True, default=list)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('question_order', models.JSONField(blank=True, default=list, help_text='List of question IDs in the order shown to the student.')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
    ]
